### ISSUE TITLE
CMS red color

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#100]
Hello,

3 things which really started to worry me while browsing tvs for few minutes:

1) top menu is really not very readable for me: http://pic.webas.lt/webas.lt-7be5829ac5.png
2) Sidebar menu - I would make it opened by default, with maybe checkbox or some button to callapse (or auto calapse as it is now). Because there is no need in so much space on full hd resolution for editing input fields.
3) NEW button probably should be colored different- I could hardly find it. but maybe it is due to Nr.1 

That's all for now:)

**Comment by RyanThompson** [comment]
1.) Eh.. it could be less crazy for sure but use it for a few moments I think you'll get used to it. Also it's not locked in AT ALL. Branding is meh right now.

2.) There will soon be an option to pin the sidebar open. Been thinking about it - it'd just be a setting.

3.) My design self says NO. My UX self says pry - but those section buttons should be floating left either way.

Feel free to continue reviewing but I am going to close this for now cause the theme is still being modified here and there. 

Also: https://github.com/anomalylabs/anomaly-theme

**Comment by RyanThompson** [comment]
Looks like you might be out of date too? The buttons are correct on mine (float right).. Update and delete your public/assets/REF
