### ISSUE TITLE
What happens after you add a Field to users?

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#101]
Hello everybody and @RyanThompson 

1 more thing started to bother me, when working with PyroCMS3.

For example we have module - Users.
I added the Field called - Company name.

Is there a way, later, to somehow sync that data?

What I am trying to say, is that now - if we wanna update clients site. we create migrations etc, upload to the server. and run migrations.

How this is going to work in PyroCMS 3?

Thanks

**Comment by RyanThompson** [comment]
You talking about 2.2.x to 3.0 update (and custom fields)?
