### ISSUE TITLE
Example usage of Table, Form, Tree builders

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#102]
Hello everyone!

Maybe someone already have tried and can share experience using Table, Form and Tree builder outside of PyroCMS?

There is one system I am working on, and I would like to use them. But looking through the code I could not get too far.

Thanks a lot in advance!

**Comment by RyanThompson** [comment]
Include the streams platform and any necessary addons / field types:
https://github.com/anomalylabs/streams/blob/1.0/develop/composer.json#L19

Then include it's service provider:
https://github.com/anomalylabs/streams/blob/1.0/develop/config/app.php#L141

That should get you close.
