### ISSUE TITLE
Just installed. Could not reach the installed - nesting level  reached 100

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#103]
Hello,

When I reach the http://pyro.app/installer

I see this: http://pic.webas.lt/webas.lt-a72fa10e4b.png

Logs show pretty much the same

**Comment by huglester** [comment]
Added this to xdebug conf:

xdebug.max_nesting_level = 500

ANd it is solved. Is it normal behaviour? Just curious?

**Comment by RyanThompson** [comment]
It is - can be typical in OOP I believe. I disable XDEBUG until I am ready to use it anymore cause it does this on vanilla Laravel too I think.

**Comment by huglester** [comment]
I will test and let you know about vanilla
