### ISSUE TITLE
Default order_by if sortable equals true

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/streams-platform#119]
If sortable is equal to true then even if order_by is not set then set order_by

        'order_by' => [
            'sort_order' => 'ASC'
        ],

**Comment by RyanThompson** [comment]
Donezo: https://github.com/anomalylabs/streams-platform/commit/3a375005f34f7f59326f40c7edb810bc0a126144

**Comment by bloveless** [comment]
So this is weird. Sortable is equal to true. When I dd the table at the end of the \Table\Command\SetDefaultOptions.php I see that the table options are set to order_by => [ 'sort_order' => 'asc' ]

![screen shot 2015-07-02 at 2 56 53 pm](https://cloud.githubusercontent.com/assets/535135/8487636/97a9a452-20ca-11e5-951e-addc0b816de7.png)

But the query in the page is still show sort by id

![screen shot 2015-07-02 at 2 57 12 pm](https://cloud.githubusercontent.com/assets/535135/8487646/a55036fc-20ca-11e5-9f8a-fc9d998a605d.png)

**Comment by RyanThompson** [comment]
Anything weird in here: 

https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Ui/Table/Command/SetDefaultOptions.php#L108

**Comment by bloveless** [comment]
Nope it looks exactly the same as what you've got.
