### ISSUE TITLE
Saving seems to save to cache but not to database

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/streams-platform#122]
This is a custom module I'm working on but I believe it is an issue somewhere.

Data is persisted to the form after a save or refresh

![screen shot 2015-07-02 at 5 51 50 pm](https://cloud.githubusercontent.com/assets/535135/8490260/234bf812-20e3-11e5-8c5c-ddee559146a2.png)

Database seems to only have the content from the initial save

![screen shot 2015-07-02 at 5 53 05 pm](https://cloud.githubusercontent.com/assets/535135/8490265/36d1f170-20e3-11e5-80ca-e61edd2aadce.png)

**Comment by RyanThompson** [comment]
So if you save, then edit and save again.. The values don't change?

**Comment by bloveless** [comment]
Correct. They seem to only change the DB values on the initial save. I just updated and cleared caches and published the assets.

**Comment by bloveless** [comment]
https://github.com/bloveless/stashes-module
