### ISSUE TITLE
Changing admin theme in admin area has no effect

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/streams-platform#123]
I just did a composer update and my admin theme was no longer being used.

`'admin_theme'  => env('ADMIN_THEME', 'anomaly.theme.anomaly')` 

in 

`streams/config/streams.php` 

is the value that is being used.  I've updated my .env file so my admin theme is being referenced again but it's confusing that updating  the theme in the admin area has no effect.  I'm not sure what the behavior is supposed to be.  if .env trumps the db value should probably just remove that field from the admin area or make it read only.

**Comment by RyanThompson** [comment]
Hey my bad dude - I should have left that in there until I was done. Added a last minute module called "Appearance" to modify / manage themes. 

For now you can set this in your .env file:

ADMIN_THEME=anomaly.theme.anomaly
STANDARD_THEME=foo.theme.awesome

**Comment by RyanThompson** [comment]
Ill have the module done tomorrow. It's basically a simple clone of the settings module with a little extra thrown in.
