### ISSUE TITLE
Bootstrap switch is not a function

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/streams-platform#130]
Editing pages and there is an issue that causes the editor field to be a regular text field.

<img width="970" alt="screen shot 2015-07-10 at 11 23 47 am" src="https://cloud.githubusercontent.com/assets/535135/8624590/35f08816-26f6-11e5-9f6d-e32fbc0e4b67.png">

**Comment by RyanThompson** [comment]
This is fixed.
