### ISSUE TITLE
Table buttons are guessing incorrectly

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/streams-platform#139]
![screen shot 2015-07-24 at 9 25 38 am](https://cloud.githubusercontent.com/assets/535135/8878431/1c5e46f2-31e8-11e5-9e64-0a1cc7bb868b.png)

![screen shot 2015-07-24 at 9 26 58 am](https://cloud.githubusercontent.com/assets/535135/8878435/1ebd614e-31e8-11e5-9e51-dd53e6d269cd.png)

Should be /admin/pages/types/fields/1

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/a5cdcf1b12793b6a1763810e9862603671b8b428

Whoops ^_^
