### ISSUE TITLE
.editorconfig

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#146]
Hello!

I think it would be a good idea to use .editorconfig.
I see lot's of places where psr2 is used incorrectly (like if(!$a)) etc.

With editor config I think it would solve more problems in the future.
What do you think?

**Comment by RyanThompson** [comment]
I have my IDE set to PSR2.. I'm surprised there are issues you've found. That said, is this for PHPStorm? I've never seen the file in use before.

**Comment by huglester** [comment]
It is now in laravel!:)

https://github.com/laravel/framework/blob/5.1/.editorconfig

**Comment by RyanThompson** [comment]
You wanna add it to PyroCMS and PR meh?
