### ISSUE TITLE
add .php_cs or phpcs.xml

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#151]
Hello,

I think it would be good idea to add 'phpcs' to the repo..
I see a lot PSR2 violations like:

"if (!$var)" should be "if (! $var)"

I think "initial" changes should be made by you, @RyanThompson, what do you think?

if you would like to use Fabiens php-cs-fixer (cs.sensiolabs.org), then config should be taken from here: https://raw.githubusercontent.com/laravel/framework/5.1/.php_cs

and just run: `php-cs-fixer fix`

Because the more far we go, we more those changes will be later

THanks

**Comment by RyanThompson** [comment]
PR meh!
