### ISSUE TITLE
Get foreign key of a related stream/entry

### ISSUE THREAD

**Issue by websemantics** [anomalylabs/streams-platform#165]
This is two problems, (1) determine if an entry is related to another, and (2) if it is, .. what is the foreign key that bonds them in a holy matrimony ..

**Comment by RyanThompson** [comment]
Note to self add getters for this in ft - public

**Comment by websemantics** [comment]
@RyanThompson, any update on this? This is what I use, 

```
    public function getForeignKey($entry)
    {
        $table = $entry->getTableName();

        $relations = $this->getRelationshipAssignments();

        foreach ($relations as $relation) {
            if ($relation->getFieldType()->getRelatedModel()->getTableName() == $table) {
                return $relation->getFieldType()->getColumnName();
            }
        }
}
```
Pretty bad huh?

**Comment by RyanThompson** [comment]
I have to get it done - it really shouldn't be hard. I've got a bunch of time tonight to devote to some input related shit so Ill hammer this in too.

**Comment by RyanThompson** [comment]
It's gonna be methods on the field type doing kinda like what you're doing.

**Comment by websemantics** [comment]
Oh good, .. at least the code wasn't a total embarrassment hh

**Comment by RyanThompson** [comment]
Welp.. so much for tonight. Maybe tomorrow night lol.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
Please move this to pyrocms/pyrocms if still applicable.
