### ISSUE TITLE
Installer module removes any existing values in `.env` file

### ISSUE THREAD

**Issue by tobz-nz** [anomalylabs/streams-platform#167]
The install module completely replaces any existing `.env` file - not ideal when trying to automate setup.
Currently I'm having to run ansible scripts to install everything - which creates the .env file, then run the pyro installer then re-create my original .env file (which includes the required values for pyro, excluding the `ADMIN_*` values).

Ideally the installer would replace any values it want to write that already exist in the `.env` and add anything else to the bottom of the file - leaving all other existing values alone.

**Comment by websemantics** [comment]
@tobz you could automate the entire installation process entirely without using the Installer-Module, giving you full control including generating your own .env, .. if you look here, https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Installer/Console/Install.php .. you will be able to identify what to automate .. mainly, a series of artisan commands ..

**Comment by tobz** [comment]
Wrong tagged person. :)

**Comment by websemantics** [comment]
I blame github hhh ..  irrelevant information unfortunatly, I'd stick with Python and Go :) .. apologies @tobz .. @tobz-nz, reply was for you ..
