### ISSUE TITLE
Streams:install command line

### ISSUE THREAD

**Issue by websemantics** [anomalylabs/streams-platform#169]
When tested, the command line won't allow for empty database password

**Comment by RyanThompson** [comment]
Try now

**Comment by RyanThompson** [comment]
PS - the command is `php artisan install` now

**Comment by websemantics** [comment]
Just did, .. same error!

Also, will be nice to feed install params somehow to automate it .. 

![invalid](https://cloud.githubusercontent.com/assets/2190455/13204587/93a0b528-d8a1-11e5-9faa-02caf0884ff9.png)

**Comment by RyanThompson** [comment]
Ya I would like to have options able to be passed in and thanks for reminding me - Ima add an issue for it. 

I don’t believe symfony’s console service has ask optional only ask with value anticipation and options. Might have to go ahead and make a password ;-)

Closing this for now but if you find anything clean that could be done reopen it / PR!

**Comment by RyanThompson** [comment]
Also issues -> Pyrocms/pyrocms now ^_^

**Comment by websemantics** [comment]
Making a password is never a bad idea hh .. will look into it and surely PR if anything .. thanks @RyanThompson
