### ISSUE TITLE
domain is down for me

### ISSUE THREAD

**Issue by assertchris** [anomalylabs/streams-platform#241]
http://anomaly.is/

**Comment by RyanThompson** [comment]
I need to remove it from the source - it's going for a bit :-/

**Comment by RyanThompson** [comment]
(the registrar was jacked up - so I let it go)

**Comment by assertchris** [comment]
righto!

**Comment by assertchris** [comment]
Congratulations on 3

**Comment by RyanThompson** [comment]
Thank you!
