### ISSUE TITLE
Multiform tries to save child form with model

### ISSUE THREAD

**Issue by daviesgeek** [anomalylabs/streams-platform#263]
I extended a MultiFormBuilder ([PageEntryFormBuilder](https://github.com/anomalylabs/pages-module/blob/master/src/Page/Form/EntryFormBuilder.php) to be specific), then added my own child form. Everything works just fine until it tries to save the form. The other two forms (EntryFormBuilder & PageFormBuilder) save just fine, but my child form breaks [here](https://github.com/anomalylabs/streams-platform/blob/a2241f8d25808bb6b7346ca497623a717ab9411f/src/Ui/Form/Command/SaveForm.php#L48) because there is no repository. I tried setting both model & save to false in the builder, as well as setting my own handler, but to no avail.

Here's the stack trace:
[laravel-2016-07-06.log.txt](https://github.com/anomalylabs/streams-platform/files/350484/laravel-2016-07-06.log.txt)

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/9dd912965a6ecd20eae9194ec902ad13f40db7d1
