### ISSUE TITLE
Foreign keys are not enforced

### ISSUE THREAD

**Issue by pepijnolivier** [anomalylabs/streams-platform#289]
When I create 2 streams, one with a relation to the other, I notice that foreign keys are not enforced on the database level.

@RyanThompson Is there a reason behind this? Can I configure the migration to enforce foreign keys?

Or could you point me in the right direction so I can send in a PR to add FK to the migrations ?

**Comment by RyanThompson** [comment]
For exactly this reason: 

> It should also be noted, that data, which serves as a foreign key in one record, cannot be removed if there is another record that assumes its existence.

From MySQL docs.

Relationships are not always a hard coupling. And should be loosely defined. Allowing another to be deleted without enforcement. 

That said. There could be a config option that causes this kind of key binding.

Please open an issue and reference this one in the main pyrocms repository though. These other repositories are read-only / PRs
