### ISSUE TITLE
JSON responses from AJAX forms

### ISSUE THREAD

**Issue by samharrison7** [anomalylabs/streams-platform#290]
If the `$ajax` property of a form is set to true, it would be good to have an AJAX request to the form's submit URL (i.e. `public/handle/form/key`) return a JSON response. It would be good also if saving the form didn't trigger any flash messages and instead the JSON could include all the relevant messages.

Other useful things to have in the response might include the entry itself, and maybe even the HTML for the form itself so the user could reload the modal with the new data. A rough idea:

```
{
"messages" : {
   "error" : "Error message",
   "warning" : "Warning message",
   "success" : "Success message"
   },
"entry" : {
   "id" : "1",
   "stream" : "Anomaly\PostsModule\Post\PostModel",
   "title" : {
      "type" : "anomaly.field_type.text",
      "value" : "Title"
   },
"form_html" : "<form>...</form>"
}
```

**Comment by RyanThompson** [comment]
Linked to main repo in pyrocms/pyrocms

https://github.com/pyrocms/pyrocms/issues/3822
