### ISSUE TITLE
Form validation and $_POSTed data

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#302]
Hello,

so we have a form. and First name is required.
we have populated data, but for example we remove the 'First name' value;
and try to save;
we get 'First name required' validation error 

but in the first_name field, we get old data, not $_POSTed one (empty).
We think that after saving the form, data in the forms should be $_POSTed not from the entity.

thanks

**Comment by RyanThompson** [comment]
Keep issues on the main repository please ^_^
