### ISSUE TITLE
Forms with criteria break when using 'array' cache driver

### ISSUE THREAD

**Issue by pepijnolivier** [anomalylabs/streams-platform#336]
When using an `array` cache driver, some forms will break (eg. the public login form).
This is because Forms rely on a persistent cache driver. This is the simplified flow:

The [FormCriteria](https://github.com/anomalylabs/streams-platform/blob/master/src/Ui/Form/FormCriteria.php#L147) class writes an entry to the cache. This entry is later retreived by the [FormController](https://github.com/anomalylabs/streams-platform/blob/master/src/Http/Controller/FormController.php#L29) and passed to the [GetFormCriteria](https://github.com/anomalylabs/streams-platform/blob/master/src/Ui/Form/Command/GetFormCriteria.php#L61) command. This last link shows the line where the code breaks. 

> The code breaks because FormFactory@make expects an array, but instead `null` is passed in

---

Proposed solution: Instead of relying on the Cache driver, it might make more sense to rely on the Session driver, although this might still break if the Session driver is then set to `array`.
Another solution might be to check if either the cache or the session driver have any persistence, and use the one that does, if available. Or rely on a Request instead.

<img width="1148" alt="public-login-form-breaks" src="https://cloud.githubusercontent.com/assets/2015108/21371324/f204cbbe-c710-11e6-9efc-a707b7c80266.png">

**Comment by RyanThompson** [comment]
All issues on the main repo please :-(

**Comment by RyanThompson** [comment]
Ill try and address this today though ;-)

**Comment by pepijnolivier** [comment]
awesome 👍 
I'll post new issues on the main repo in the future, sorry about that :-)
