### ISSUE TITLE
Table filter definition properties - class not found

### ISSUE THREAD

**Issue by kiltedup** [anomalylabs/streams-platform#373]
When adding filters to a table, setting properties such as 'heading', 'query', 'filter' etc throws a **class not found error**. Happens on column filters, custom filters but NOT search.

e.g.

```
protected $filters = [ 
    'title' => [ 
        'heading' => 'Just Testing', 
    ] 
];
```

results in : 

`ReflectionException thrown with message "Class title does not exist"`

**Comment by Piterden** [comment]
```php
protected $filters = [ 
    'title' => [
        'filter'   => 'input',
        'placeholder' => 'Just Testing',
        'query' => GenericFilterQuery::class,
        'prefix' => 'filter_',
    ] 
];
```
`/vendor/anomaly/streams-platform/src/Ui/Table/Component/Filter/Contract/*`
`/vendor/anomaly/streams-platform/src/Ui/Table/Component/Filter/FilterNormalizer.php`

**Comment by RyanThompson** [comment]
You need to define what kind of filter it is like you did in the second example.
