### ISSUE TITLE
fatal error when running php artisan migrate:status

### ISSUE THREAD

**Issue by mjrider** [anomalylabs/streams-platform#391]
i get the following error on running artisan migrate:status
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function getAddon() on null   
```
this traces back to
https://github.com/anomalylabs/streams-platform/blob/master/src/Database/Migration/MigrationRepository.php#L29

The problem is that it doesn't check if migrator is still null.

**Comment by RyanThompson** [comment]
Wrong repository - sorry! Please keep these in the main pyrocms/pyrocms repo ^_^
