### ISSUE TITLE
BaseController

### ISSUE THREAD

**Issue by lenssoft** [anomalylabs/streams-platform#404]
In the latest version the VerifyCsrfToken middleware is not being filtered out in the BaseController. This cause my app to crash ( HTTP 302 no log no error nothing) . The source of the problem was  commited probably at https://github.com/anomalylabs/streams-platform/commit/80f44cc60999a8d30182f5b3d61aab51c033847f

when a new middleware was introduced.

Please correct it. I think the right behavior for the resource controller is to skip the  csrftoken validation.

Thanks in advance.

**Comment by RyanThompson** [comment]
Fixed - thank you for the heads up!

PS please keep all issues in the main github.com/pyrocms/pyrocms/issues list.

Thanks!
