### ISSUE TITLE
Problems with fresh installation - Fatal error in Formbuilder

### ISSUE THREAD

**Issue by markbratanov** [anomalylabs/streams-platform#58]
Still can't seem to install, been at it for a few days, checking out the latest versions hoping one would work. Checked out one today (2nd of Jan) and ran composer update. 

**Receive the following exception while running composer update:**    
```
Generating autoload files 
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Trait 'Illuminate\Support\Traits\Macroab
le' not found' in C:\wamp\www\streams\vendor\illuminate\html\FormBuilder.php:9
Stack trace:
#0 C:\wamp\www\streams\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(118): Illuminat
e\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}
Script php artisan clear-compiled handling the post-update-cmd event returned with an error
  [RuntimeException]
  Error Output:
```

**The following error while running GUI install in browser:**  
```
FatalErrorException in FormBuilder.php line 9:
Trait 'Illuminate\Support\Traits\Macroable' not found 
at HandleExceptions->fatalExceptionFromError(array('type' => '1', 'message' => 'Trait 'Illuminate\Support\Traits\Macroable' not found', 'file' => 'C:\wamp\www\streams\vendor\illuminate\html\FormBuilder.php', 'line' => '9')) in HandleExceptions.php line 118
at HandleExceptions->handleShutdown()
```

Any help / guidance to bypass the installer would be appreciated.

**Comment by RyanThompson** [comment]
The quick fix is to modify this manually in the FormBuilder and HtmlBuilder classes in Illuminate. There have been traits changes in L5 that caused the HTML updates. Ill either push a composer @commit to use or update to the latest L5 but.. I think there is a lot of broken stuff in 3rd party packages for L5. Not sure.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by ChristianGiupponi** [comment]
Same problem

**Comment by RyanThompson** [comment]
Git pull streams then composer update. L5.

**Comment by RyanThompson** [comment]
This was just resolved last night with a commit alias for illuminate/html and should work fine now.

**Comment by ChristianGiupponi** [comment]
Where should I run that command?

```
iMac-di-Christian:PyroCMS christiangiupponi$ git pull
Already up-to-date.
iMac-di-Christian:PyroCMS christiangiupponi$ pwd
/Users/christiangiupponi/vagrant/Homestead/www/PyroCMS
iMac-di-Christian:PyroCMS christiangiupponi$ git pull streams
fatal: 'streams' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
iMac-di-Christian:PyroCMS christiangiupponi$ 
```

**Comment by RyanThompson** [comment]
git clone git@github.com:anomalylabs/streams.git

And "git pull" doesn't need streams. Just make sure you are in that repo.
