### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#60]
Probably here:

        "twig/twig": "1.16.*@dev",
        "rcrowe/twigbridge": "0.6.*",
        "barryvdh/laravel-debugbar": "1.*",
        "barryvdh/laravel-ide-helper": "1.11.*@dev",
        "coffeescript/coffeescript": "1.3.1",
        "michelf/php-markdown": "1.4.1",
        "aptoma/twig-markdown": "0.2.*",
        "guzzlehttp/guzzle": "~4.0",
        "intervention/image": "2.0.14",
        "jenssegers/agent": "2.1.4",
        "kriswallsmith/assetic": "1.2.*@dev",
        "leafo/scssphp": "0.1.0 ",
        "lmammino/jsmin4assetic": "1.0.*@dev",
        "natxet/CssMin": "3.0.*@dev",
        "nesbot/Carbon": "1.*",
        "oyejorge/less.php": "~1.5",
        "ptachoire/cssembed": "1.0.2",
        "phpseclib/phpseclib": "0.3.*@dev",
        "robclancy/presenter": "1.3.*",
        "filp/whoops": "~1.0",
        "symfony/yaml": "2.7.*@dev",
        "laracasts/commander": "~1.0",
        "way/generators": "~3.0",
        "dimsav/laravel-translatable": "5.0.*@dev",
        "venturecraft/revisionable": "1.*"

all this strictness should be removed? where cold of... for example:
"intervention/image": "2.0.14",
should become:
"intervention/image": "~2.0",

"ptachoire/cssembed": "1.0.2",
to:
"ptachoire/cssembed": "~1.0",

what do you think?

**Comment by RyanThompson** [comment]
Yes we don’t need to designate patches - those are (according to semantic versioning) 100% compatible version changes.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
What's the scoop here? Getting anywhere?

**Comment by huglester** [comment]
For this package I updated to this, and sorted alpahbeticly:

https://github.com/huglester/streams-platform/commit/a797230b6fb3b07f02fc4c9b32473f98e80e767f

Trying to build the `streams` repo to make sure everything works..
 on my home VM it takes  with i7 and 16gb of ram it takes > 20mins, this PC is killing me :D

So this is kinda time consuming :(

**Comment by RyanThompson** [comment]
Yikes!


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581
