### ISSUE TITLE
Installation from zip

### ISSUE THREAD

**Issue by ChristianGiupponi** [anomalylabs/streams-platform#62]
After fill up the installation form I get:

![screencapture-pyrocms-app-8000-installer](https://cloud.githubusercontent.com/assets/1614796/5735966/9da40788-9bcf-11e4-83b2-e020fa29351b.png)

**Comment by websemantics** [comment]
Had the same here, but I moved passed that by filling the password field with temp text '1234' then removing it after the database.php config file was generated.
However, I had another error:
![error](websemantics.ca/temp/screencapture-localhost-8000-installer.png)

**Comment by websemantics** [comment]
I had the same when the db password is empty

**Comment by RyanThompson** [comment]
Will touch this tonight for you guys.

**Comment by websemantics** [comment]
Ok, here's where this got me, .. 

The issue is with the Illuminate\Bus\Dispatcher class,

Line: 133
```		$value = $this->extractValueFromExtras($parameter, $extras)
								?: $this->extractValueFromSource($source, $parameter);```

This will return 'null' when the password is empty. Which makes it a Laravel bug?!

And, it could be fixed, by assigning a default value to the password on the GenerateDatabaseFile constructor, 

    function __construct($driver, $host, $database, $username, $password = '')

**Comment by RyanThompson** [comment]
Heh - no that's too deep: https://github.com/anomalylabs/streams-distribution/blob/master/src/Command/GenerateDatabaseFile.php

The construct should have null as a default.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-distribution/commit/b968615f1bd38ef38d072e510889bab5d83adfd9
