### ISSUE TITLE
Edit link invalid URL

### ISSUE THREAD

**Issue by dakshhmehta** [anomalylabs/streams-platform#63]
Hello,

The button "edit" is guessing wrong URL.

Install path: http://domain/lab/pyrocms
Guess Path: http://domain ( lab/pyrocms is skipped )

Thanks.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/2cc9ebc9c91e420ac1ce24f09ed3afe582db0e8a
