### ISSUE TITLE
Dispatcher doesn't allow null value at GenerateDatabaseFile

### ISSUE THREAD

**Issue by ramon-villain** [anomalylabs/streams-platform#65]
I'm working locally, so I don't set any password. Can I set a null value as a 'DefaultValue' for the db_password? 

````
Unable to map parameter [password] to command [Anomaly\StreamsDistribution\Command\GenerateDatabaseFile]
````
I'm getting this message

**Comment by RyanThompson** [comment]
Doop: https://github.com/anomalylabs/streams-platform/issues/62

**Comment by ramon-villain** [comment]
my bad :(

**Comment by RyanThompson** [comment]
Ill get this fixed tonight - you can add a null here though: https://github.com/anomalylabs/streams-distribution/blob/master/src/Command/GenerateDatabaseFile.php#L16

**Comment by RyanThompson** [comment]
All good! I do it all the time ^_^
