### ISSUE TITLE
Relationship field type, formbuilder on post: Column not found error

### ISSUE THREAD

**Issue by RobinRadic** [anomalylabs/streams-platform#66]
I am have created a module with a stream, fields etc.

However, i have some problems getting the relationship field type working. It gets stuck on inserting records. The relationship field type automaticly adjusts the 'user' field name to 'user_id' as  column name. As a result, when the FormBuilder->render() handles a POST request, i get the following error:

`Column not found: 1054 Unknown column 'user' in 'field list' `.

As temporary workaround i've altered the `Anomaly\RelationshipFieldType\RelationshipFieldType.php` file. Then it works perfectly.
```php
    public function getColumnName() {
        //return parent::getColumnName() . '_id';
        return parent::getColumnName();
    }
```

Am i doing something wrong or is this a bug?

Here's some of my other code
```php

class CharactersFieldInstaller extends FieldInstaller
{
    protected $fields = [
        'name'             => 'text',
         'user'             => [
            'type'   => 'relationship',
            'config' => [
                'related' => 'Anomaly\UsersModule\User\UserModel',
            ],
        ],
    ];
}
```

```php
class CharactersStreamInstaller extends StreamInstaller
{
    protected $stream = [
        'slug'         => 'characters',
        'title_column' => 'name',
    ];
    protected $assignments = [
        'name'         => ['required' => true, 'unique' => true],
        'user'         => ['required' => true]
    ];
}
```

```php
class CharacterFormBuilder extends FormBuilder
{
    protected $model = 'Radic\MyModule\Character\CharacterModel';
    protected $fields = 'Radic\MyModule\Character\Ui\Form\Handler\FieldsHandler@handle';
}
```

```php
class FieldsHandler
{
    public function handle()
    {
        return [ 'name', 'user' ];
    }
}
```

Thanks :smiley:

**Comment by RyanThompson** [comment]
Hi Robin,

I am aware of this unfortunately. It’s on my list of things today to figure out if I am going to decouple the input / filter / mutation methods for Field Types off the primary class into other classes (i.e. FieldTypeInput, FieldTypeFilter, FieldTypeHandler).

This will be remedied quickly I assure you as it’s one of my top priorities. 

Sorry!


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
This should be fixed by now - will need to re-install!
