### ISSUE TITLE
Clean install, no routes

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/streams-platform#67]
just did a clean clone of streams and composer install.  everything went fine, but when i navigated to the site in my browser i just get 404.  running artisan route:list doesn't show an installer route either.

**Comment by RyanThompson** [comment]
Hey Matt! Good to see you’re back checking in ^_^

Did you route your installation to the public/ folder?

And remember you should clone down streams or pyrocms base packages and not the streams-platform one.

**Comment by mattcdavis1** [comment]
yeah - definitely cloned streams and my vhost was pointing to public (i put a die in public/index.php to verify).  I tried another clean install just now but i'm getting "Your requirements could not be resolved to an installable set of packages." when i try and run composer install.

**Comment by RyanThompson** [comment]
This just popped up last night - I believe it’s related to Taylor moving Laravel to 5


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is

t (877) 705-0806
m (309) 752-8581

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/9e3c2a18cb3aa6d45b03b87165bc94d9e7effccb Fixed
