### ISSUE TITLE
Get schema from model / set schema connection based on model

### ISSUE THREAD

**Issue by websemantics** [anomalylabs/streams-platform#68]
Hi Ryan

If one wants to support multiple-database connections for Streams, .. for example, each Namespace is assigned to different DB connection, ..  Would Streams Core be able to support that? .. If not, can we add this feature in? .. The Stream Schema then has to read the DB connection from the Model to be able to adjust Table structure.

If that makes any sense :)

Best

Adnan

**Comment by RyanThompson** [comment]
Uhhh note to self: Get connection for schema from model during table manipulations.

^_^

**Comment by RyanThompson** [comment]
http://laravel.com/api/4.1/Illuminate/Database/Eloquent/Model.html#method_getConnection
https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Stream/Command/Handler/CreateStreamsEntryTableHandler.php

**Comment by websemantics** [comment]
Thank you Ryan, .. 
What if the Stream is setup with an optional db connection?

**Comment by websemantics** [comment]
Also, regarding relationships across DBs, here's what Laravel docs has to say:

`Be careful about attempting to build relationships with tables across databases! It is possible to do, but it can come with some caveats and depends on what database and/or database settings you have`

**Comment by RyanThompson** [comment]
Please move this to pyrocms/pyrocms if still applicable.
