### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ramon-villain** [anomalylabs/streams-platform#73]
Even checking everything I still unable to install a fresh new version. Am I missing something?
Step-to-step below.

![screen shot 2015-02-25 at 01 04 58](https://cloud.githubusercontent.com/assets/1520006/6364797/c3069d48-bc8a-11e4-984d-0f826bd0ea6a.png)
![screen shot 2015-02-25 at 01 05 33](https://cloud.githubusercontent.com/assets/1520006/6364798/c5f70308-bc8a-11e4-9f55-37bb961c328d.png)
![screencapture-pyro-dev-installer](https://cloud.githubusercontent.com/assets/1520006/6364799/d35ea438-bc8a-11e4-87d8-c460a07ad709.png)
![screen shot 2015-02-25 at 01 07 46](https://cloud.githubusercontent.com/assets/1520006/6364802/d9f4255c-bc8a-11e4-9231-b0f32275a1cf.png)
![screencapture-pyro-dev-installer-complete](https://cloud.githubusercontent.com/assets/1520006/6364845/805e0a20-bc8b-11e4-9a76-98e3cd307ed0.png)

**Comment by RyanThompson** [comment]
Did you get pull? I pushed a small fix that might affect this. Can you reach /admin after you see this error? I am guessing you might but chances are your users table is empty.

**Comment by ramon-villain** [comment]
Yes I did full.
I can reach /admin if I change 'SetModuleStatesHandler.php, SetExtensionStatesHandler.php, SettingsSettingsEntryModel.php' updating the table value (to default_xxxx). But once in /admin page, and  try to login I get the same issue for users' table

**Comment by ramon-villain** [comment]
The prefix (related to the app reference) in tabelas name is required ?

**Comment by RyanThompson** [comment]
The prefix issue / reference should be fixed now - working on wrapping languages in services cause user rules fails. The install will go through and the user created but the roles won't - so you can technically log in at this point.

**Comment by RyanThompson** [comment]
Yes

On Feb 25, 2015, at 9:15 PM, Ramon Villain <notifications@github.com<mailto:notifications@github.com>> wrote:


The prefix (related to the app reference) in tabelas name is required ?
