### ISSUE TITLE
(v1.8) Asset Manager Filter Registry

### ISSUE THREAD

**Issue by RyanThompson** [anomalylabs/streams-platform#732]
Hello! We have purposefully removed PHP compilation of SASS/SCSS and other compiled languages like Coffee Scripts.

I would like to implement a filter registry where you can add this functionality to your project simply by registering the filter with the asset manager.

_Originally posted by @RyanThompson in https://github.com/laravel-streams/streams-core/issues/729#issuecomment-779977880_

**Comment by spektra2147** [comment]
we are using scss then we can't upgrade to 3.8 @RyanThompson . if its going to take time can you just add scss extension again
