### ISSUE TITLE
EloquentAdapter::make() and EloquentAdapter::newInstance() returns an Model instance

### ISSUE THREAD

**Issue by BubeCPH** [anomalylabs/streams-platform#736]
`\Streams\Core\Criteria\Adapter\EloquentAdapter::make()` and `EloquentAdapter::newInstance()` returns a Model instance instead of an EntryInterface instance.

Therefore I get exceptions like this one:
_Streams\Core\Criteria\Adapter\EloquentAdapter::make(): Return value must be of type Streams\Core\Entry\Contract\EntryInterface, App\Models\TransmissionType returned_

**Comment by BubeCPH** [comment]
If I have missed something, catch me on Discord

**Comment by BubeCPH** [comment]
A solution could be:
Remove model creation in newInstance() and return newInstance in make() in the file src/Criteria/Adapter/EloquentAdapter.php

**Comment by RyanThompson** [comment]
The model, with Streams, carries the entry interface now.
