### ISSUE TITLE
composer installation issues with larval 9 

### ISSUE THREAD

**Issue by abdallahmaali** [anomalylabs/streams-platform#738]
composer require streams/core 

    - streams/core[v1.9.0, ..., 1.10.x-dev] require laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.2).
    - Root composer.json requires streams/core ^1.9 -> satisfiable by streams/core[v1.9.0, ..., 1.10.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

my Laravel version is 

Laravel Framework 9.5.1

**Comment by RyanThompson** [comment]
Only the 2.0 (currently dev) branch supports the latest laravel
