### ISSUE TITLE
Psr2?

### ISSUE THREAD

**Issue by huglester** [anomalylabs/streams-platform#76]
Hello,

I think it would be good shot to move right along to psr2, you probably already saw the news. it is just a reminder :) 

Thanks!

**Comment by RyanThompson** [comment]
I am pretty sure the entire codebase is PSR2 compliant. Do you see anything otherwise?

**Comment by huglester** [comment]
php-cs-fixer --dry-run fix . --level=psr2 complains a little bit on this repo. I just don't wanna do any pull requests or something while there are still pending ones

**Comment by RyanThompson** [comment]
Ah - ya I usually do that afterward but am in the tail end of fixing translations. No worries it will all be PSR 2 ^_^

On Feb 25, 2015, at 6:19 AM, huglester <notifications@github.com<mailto:notifications@github.com>> wrote:


php-cs-fixer --dry-run fix . --level=psr2 complains a little bit on this repo. I just don't wanna do any pull requests or something while there are still pending ones

**Comment by huglester** [comment]
okay, just wanted to be sure if we are following it :)
maybe it would be good to connect something like: http://fabbot.io/ for pull requests. if it is possible, not used to be honest :)

**Comment by RyanThompson** [comment]
That looks cool! But I will just use my IDEs sniffer and the CS tool ^_^

Thanks!

On Feb 25, 2015, at 6:48 AM, huglester <notifications@github.com<mailto:notifications@github.com>> wrote:


okay, just wanted to be sure if we are following it :)
maybe it would be good to connect something like: http://fabbot.io/ for pull requests. if it is possible, not used to be honest :)
