### ISSUE TITLE
Install Errror

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/streams-platform#77]
Just did a clean clone / composer install and i'm getting an error when running streams installer:

production.ERROR: exception 'ErrorException' with message 'Argument 3 passed to Anomaly\Streams\Platform\Database\Migration\Command\Handler\MigrateAssignmentsHandler::assignField() must be of the type array, string given, called in {path/to/app}/vendor/anomaly/streams-platform/src/Database/Migration/Command/Handler/MigrateAssignmentsHandler.php on line 47 and defined' in {path/to/app}/vendor/anomaly/streams-platform/src/Database/Migration/Command/Handler/MigrateAssignmentsHandler.php:59

**Comment by mattcdavis1** [comment]
i'm guessing i probably should have posted this under streams rather than streams-platform but either way just wanted to add a debug screenshot: https://www.evernote.com/shard/s50/sh/c9e939c3-e66a-4fe1-98da-e170b443239a/58f969b71ca18b1cb2e65ab0c58ca09e

looks like line 43 is getting the wrong thing returned (string instead of array)

**Comment by mattcdavis1** [comment]
so, to resolve this issue i changed the streams property in the users-module AnomalyModuleUsers_100_alpha_CreateProfilesStream migration to:

protected $stream = [
        'slug'         => 'profiles',
        'title_column' => 'display_name',
    ];

this fixed one issue but then i ran into another which was related to the UserModel not implementing methods getId() and roles().  to temp fix this i added:

public function getId()
    {
        return $this->id;
    }

    public function roles()
    {
        return parent::roles();
    }

to UserModel.

This fixed that issue but then i got an issue: Unknown column 'email' in 'field list'

**Comment by RyanThompson** [comment]
This will all be fixed tonight - I might have some missing commits but this has been resolved. Ill be pushing serious core installer improvements / fixes in a bit.

**Comment by mattcdavis1** [comment]
k great!  I'm hoping to get some module development over the weekend.

**Comment by RyanThompson** [comment]
Me too! Hit me up tomorrow and I will show you the changes. Installers are gone in favor of migrations / seeders in addons now.

On Feb 27, 2015, at 9:37 PM, Matt Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


k great! I'm hoping to get some module development over the weekend.

**Comment by RyanThompson** [comment]
Good to go!
