### ISSUE TITLE
Migration Issues.

### ISSUE THREAD

**Issue by websemantics** [anomalylabs/streams-platform#80]
Here's a number of issues with Migrations, 

(1) When un-installing a module (migration down), the translations of streams/fields and assignments don't get deleted, .. also Streams are not deleted,  
(2) Streams translations are stored in two db rows (one with name filled-in, other with description)
(3) Assignments translations are stored in three db rows (label, instructions and placeholder).

**Comment by RyanThompson** [comment]
Donezo
