### ISSUE TITLE
Users, Settings, Preference, Blog Modules Error on Clean Install

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/streams-platform#83]
Just did a clean clone / install of streams and getting 500 on users module, settings module, preferences module, blog module

https://www.evernote.com/shard/s50/sh/d54fe0d3-02fc-4712-99a9-e6a8c2e37535/771787f29ac04b25eb53bf3c3bcc7c0e

https://www.evernote.com/shard/s50/sh/de3cc466-3c05-46a1-ac62-259f23d236ee/b31efc61251a2e0cb24ff1c78996727a

https://www.evernote.com/shard/s50/sh/e05a39ff-9c2a-488b-aeaa-a7321e62647b/2198d17da70a42c24ce3a1283a4198f0

**Comment by obrignoni** [comment]
Looks to me like you have to do a composer update. The last exception shows a reference to the Distributions and we removed them recently. Composer update. Delete your .env file and reinstall.
 Let me know if that helps.

**Comment by mattcdavis1** [comment]
this was a clean install so there wasn't any .env to begin with.  It sounds like Ryan was able to reproduce this on his end and is working on it though.

**Comment by RyanThompson** [comment]
All references to distributions have now been removed.

**Comment by mattcdavis1** [comment]
have you pushed all these changes yet?  rm -rf of streams + clone and install still gives me 500 when clicking on users module.

**Comment by mattcdavis1** [comment]
this is working for me as of current build
