### ISSUE TITLE
Date Field Type not saving + CSS Issues

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/streams-platform#85]
for the date field type, the value is not being mutated before saving to the db so there is an "Invalid datetime format" sql error being generated on save.  Not sure if javascript is supposed to handle formatting this value client side or if this is supposed to be handled server side.

Also, looks like some missing css for the date picker.

https://www.evernote.com/shard/s50/sh/6db2e7af-d820-4067-a31d-2fbf744aa231/9a6ba6328de59f0da3c94573903af0c4

**Comment by mattcdavis1** [comment]
got this functional by adding DateTimeFieldTypeModifier and updating css / js with from bootstrap-datetimepicker site.  Still some minor css issues but pretty much functional.

**Comment by RyanThompson** [comment]
Fixed this a bit ago ^_^
