### ISSUE TITLE
(what should be) 404s produces 500s

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/streams-platform#87]
for example, admin/dashboard/foo generates 500

https://www.evernote.com/shard/s50/sh/737ae0db-dfe7-4609-ad92-ffa6b7b33929/e61bde19afa3f3de0d2ab765ee4749c5

**Comment by mattcdavis1** [comment]
this issue may be more significant than just a wrong response code.  I've been running out of memory on my machine recently and have noticed that when i hit these what-should-be-404 pages my apache memory starts climbing really high.

When i force quit the high-memory apache processes and browse non-404 pages, what is see are processes running at appx 10MB vs 1.2GB after hitting a few non-existent pages.

https://www.evernote.com/shard/s50/sh/b1b5076a-3432-42cd-86e0-a0413d80274e/cc12dd31c90fccbd81f3494873b602fc

**Comment by RyanThompson** [comment]
Do you have any other routing that might be colliding? If you enable debugging what is the resulting error code?

http://pasteboard.co/21uVmGiT.png

**Comment by mattcdavis1** [comment]
this was  a clean install of streams with nothing added.  Here's a screenshot of the error with debugging enabled:

https://www.evernote.com/shard/s50/sh/3130b78e-b426-4676-bb2b-724ae9851342/ba05674cbe600f7394027146e4d4afd1

**Comment by mattcdavis1** [comment]
oh wait - that's actually different.  before it was 500

**Comment by RyanThompson** [comment]
Perhaps disable modules you have while testing. See if there is an anomaly in there.

On Mar 23, 2015, at 1:11 PM, Matt Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


oh wait - that's actually different. before it was 500

**Comment by mattcdavis1** [comment]
well, since this is a clean install there are no custom modules to disable.  I did rm -rf on the directory, cleared my composer cache and dropped my database.  So everything was completely fresh but i'm still getting 4-5 second load times for 404s.

**Comment by RyanThompson** [comment]
Hmm.. Something has gone awry.

On Mar 23, 2015, at 2:03 PM, Matt Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


well, since this is a clean install there are no custom modules to disable. I did rm -rf on the directory, cleared my composer cache and dropped my database. So everything was completely fresh but i'm still getting 4-5 second load times for 404s.

**Comment by RyanThompson** [comment]
Are you still getting this?

**Comment by mattcdavis1** [comment]
yes, except now it's back to 500 on memory limit exceeded.  tested using the following path:

https://www.evernote.com/shard/s50/sh/aca1b5d9-cd78-4f93-a12f-82080ee6bd20/cd97195a0516ecf791de2d6038315999

**Comment by mattcdavis1** [comment]
what's weird is that it gets to line 145 of RouteCollection quickly but the time between where it throws the exception in line 145 of RouteCollection and Line 90 of Illuminate/foundation/http/kernel where it renders the response is about 4 seconds:

Throw Not Found Exception: 323.846 (line 145 of RouteCollection.php)
Render Not Found Exception: 4,497.038 (line 90 of Kernel.php)

**Comment by RyanThompson** [comment]
It gets here quickly? https://github.com/laravel/framework/blob/8865d2276be94f0a3497ba3bd26c906ae9e91e1c/src/Illuminate/Routing/RouteCollection.php#L145

**Comment by mattcdavis1** [comment]
yes

**Comment by mattcdavis1** [comment]
i just tested on a remote server and did not experience this issue using the same codebase.  Going to try another macbook pro and see if it's specific just to my machine.

**Comment by mattcdavis1** [comment]
Looks like it's something on my machine.  checked on two other developers machines and they weren't having any problems.

**Comment by RyanThompson** [comment]
Shwoo

On Mar 24, 2015, at 3:21 PM, Matt Davis <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like it's something on my machine. checked on two other developers machines and they weren't having any problems.
