### ISSUE TITLE
Translatable error on all streams

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/streams-platform#88]
just did composer update and all the streams are breaking due to translation model error:

https://www.evernote.com/shard/s50/sh/b63c8148-7953-420a-ab78-2b0ace9efe57/0c6521c400dddd76a03b2f42d9623f36

**Comment by RyanThompson** [comment]
Recompile / install. I had to add a $translatedAttributes to the entry models for performance reasons.

**Comment by RyanThompson** [comment]
I think `php artisan migrate:refresh` should do it.

**Comment by mattcdavis1** [comment]
for some reason `php artisan migrate:refresh` always fails for me on 'highwoods.default_streams_assignments doesn't exist` so i wiped the database, did a composer update and ran the installer again.  however, i'm still getting this issue.

**Comment by RyanThompson** [comment]
On it.

**Comment by mattcdavis1** [comment]
looks like this is fixed.  working fine for me now.

**Comment by RyanThompson** [comment]
fe25ec74b755786d151b016dbb51ef4ee0bfb691 Sorry should have closed!
