### ISSUE TITLE
Polymorphic Field Type Route breaks admin area

### ISSUE THREAD

**Issue by mattcdavis1** [anomalylabs/streams-platform#89]
apparently there is an issue when using an array for a route in an addon service provider.  when i comment-out the below code in the PolymorphicFieldTypeServiceProvider class (or add a non-array route), the admin area is no longer broken.

https://www.evernote.com/shard/s50/sh/fef29427-5f5d-4725-870c-b2adb7b6116d/ed0cd7c77d4b364b33fe7e5acc65ec50

```
protected $routes = [
        'anomaly/field_type/polymorphic/search' => [
            'uses' => 'Anomaly\PolymorphicFieldType\PolymorphicFieldTypeController@search',
            'as'   => 'anomaly.field_type.polymorphic.search'
        ],
    ];
```

**Comment by RyanThompson** [comment]
Ya this should not have been committed - Ill let Oz know and revert it real quick.
