### ISSUE TITLE
Required PHP extensions

### ISSUE THREAD

**Issue by lellimecnar** [anomalylabs/streams-platform#98]
I just finished setting up a completely barebones server (FreeBSD jail), and have come up with a list of required PHP extensions. While incomplete, it's a start:

- curl
- dom
- fileinfo
- filter
- gd
- json
- mbstring
- mcrypt
- openssl
- pdo
- pdo_mysql
- tokenizer
- zip

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/installer-module/commit/171ea24849001004a2364c3f54d3ba762968d3ee
