### ISSUE TITLE
On fresh install, ReflectionException: Class composer does not exist

### ISSUE THREAD

**Issue by RobinRadic** [anomalylabs/streams-platform#99]
By doing:
```sh
git clone https://github.com/anomalylabs/streams
cd streams
composer install
php artisan
```

The following error occurs:
`[2015-04-19 02:37:13] production.ERROR: exception 'ReflectionException' with message 'Class composer does not exist' in /home/radic/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php:776
Stack trace:
#0 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('composer')
#1 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('composer', Array)
#2 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('composer', Array)
#3 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(1231): Illuminate\Foundation\Application->make('composer')
#4 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php(98): Illuminate\Container\Container->offsetGet('composer')
#5 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(773): Illuminate\Foundation\Providers\ArtisanServiceProvider->Illuminate\Foundation\Providers\{closure}(Object(Illuminate\Foundation\Application), Array)
#6 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build(Object(Closure), Array)
#7 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('command.app.nam...', Array)
#8 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Console/Application.php(108): Illuminate\Foundation\Application->make('command.app.nam...')
#9 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Console/Application.php(123): Illuminate\Console\Application->resolve('command.app.nam...')
#10 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php(171): Illuminate\Console\Application->resolveCommands(Array)
#11 [internal function]: Illuminate\Support\ServiceProvider->Illuminate\Support\{closure}(Object(Illuminate\Console\Application))
#12 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(218): call_user_func_array(Object(Closure), Array)
#13 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Console/Application.php(44): Illuminate\Events\Dispatcher->fire('artisan.start', Array)
#14 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(210): Illuminate\Console\Application->__construct(Object(Illuminate\Foundation\Application), Object(Illuminate\Events\Dispatcher), '5.0.27')
#15 /home/radic/streams/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(94): Illuminate\Foundation\Console\Kernel->getArtisan()
#16 /home/radic/streams/artisan(46): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 {main} `

As temporary workaround i added `Illuminate\Foundation\Providers\ComposerServiceProvider` to the `providers` array in `config/app.php` which  resolves the issue,

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/streams-platform/commit/e99eaeb3e04ffcad65b6d5c0096fbdbe6f265f82
